api/src/.env, api/src/Config/config.js, api/src/Config/db.js
Se agrega archivo de configuracion con valores por defecto por si no hay .env, se agrega db.js para configurar sequelize
=> Se hace un merge por que necesito datos de los modelos, archivo db.js no esta terminado aun!

api/src/routes/supplier/controllers/updateCourt.js, api/src/routes/user/controllers/getCourts.js, api/src/routes/user/controllers/updateUser.js, api/src/routes/user/user.js
controladores: updateCourt, getCourts, updateUser
=> algunos controladores

api/src/routes/supplier/controllers/register.js, api/src/utils/middlewares/setHeaders.js, client/src/Actions/actions.js, client/src/Components/Registro.jsx, client/src/Reducer/index.js
Se actualizo el reducer y las acciones. Se dejo ando el componente registro, hay que mejorar el css y otros detalles.
=> Mirrow front belu

api/src/models/Field.js, api/src/routes/index.js, api/src/routes/supplier/controllers/createCourt.js, api/src/routes/supplier/controllers/updateCourt.js, api/src/routes/supplier/court.js, api/src/routes/supplier/supplier.js, api/src/routes/user/controllers/getCourts.js, api/src/routes/user/court.js, api/src/routes/user/user.js
Rutas createCourt y updateCourt de supplier y getCourts junto a updateUser de user están funcionando.
Falta ver el tema de la carga de la imagen de la cancha (del supplier) y el tema de traer las canchas por el usuario por coordenadas.
=> Rutas lu b2

client/package.json, client/src/Components/Navbar.jsx
Hice componente Navbar e instalé react-icons.
=> componente Navbar

client/src/App.js, client/src/Components/History.jsx, client/src/Components/Navbar.jsx, client/src/Components/Settings.jsx
Rutas en App, Nav de Supplier, componentes History, Settings
=> Panel de Proveedor

api/src/routes/supplier/controllers/register.js, api/src/utils/middlewares/setHeaders.js, client/src/Components/Navbar.jsx, client/src/Components/Settings.jsx, client/src/Css/navbar.css, client/src/Styles/settingsSupplier.js
Cambios realizados de Css en Navbar y SettingSupplier. Tener en cuenta que en los headers se cambio y dejo comentadas las rutas especificas.
=> Mirror rama testeo

api/index.js, api/src/models/Field.js, api/src/models/Supplier.js, api/src/routes/index.js, api/src/routes/supplier/controllers/register.js, api/src/routes/user/controllers/deleteUser.js, api/src/routes/user/controllers/getCourtByName.js, api/src/routes/user/court.js, api/src/routes/user/user.js
Se agrega ruta de deleteUser y se borra la propiedad de lastname en Proveedor
=> Rutas lub3

api/index.js, api/src/models/Payments.js, api/src/routes/index.js, api/src/routes/supplier/controllers/createPayment.js, api/src/routes/supplier/controllers/deletePayment.js, api/src/routes/supplier/controllers/getPayment.js, api/src/routes/supplier/controllers/updatePayment.js, api/src/routes/supplier/payments.js
Se agregan GET, PUT, POST y DELETE en a ruta / supplier/payments y se corrige modelo Payments.
=> Payment routes

api/src/routes/user/controllers/updatePassword.js, api/src/routes/user/user.js
Creé controlador updatePassword para modificar la contraseña del usuario.
Agregué ruta put("/user/user/password/:id").
=> controlador y ruta updatePassword

client/src/Actions/actions.js, client/src/Components/Contact.jsx, client/src/Components/CourtCreation.jsx, client/src/Components/Home.jsx, client/src/Components/Settings.jsx, client/src/Reducer/index.js
Cambios en Componente Settings, Se agrega Componente Contact de home. Se agregan acciones y rutas relacionadas al cambio del perfil del supplier.
=> Mirrow belu contacto front

api/src/routes/supplier/controllers/deleteCourt.js, api/src/routes/supplier/controllers/getCourts.js, api/src/routes/supplier/court.js
Se agrega ruta de "deleteCourt" y "getCourts" por Id de proveedor
=> Rutas lub6

api/src/routes/supplier/controllers/courtDetail.js, api/src/routes/supplier/controllers/getCourts.js, api/src/routes/supplier/court.js
Ruta y controlador para traer el detalle de la cancha para el supplier
=> ruta y controlador de traer el detalle de la cancha para el supplier

api/src/routes/supplier/controllers/availability/getAvailabilityCourt.js, api/src/routes/supplier/controllers/availability/helpers/noRepeatedDays.js, api/src/routes/supplier/controllers/updatePassword.js, api/src/routes/supplier/supplier.js
Agregué función organizadora en getAvailabilityCourt.
Arreglé controlador de actualizar la contraseña (user).
Controlador y ruta para actualizar la contraseña del proveedor.
=> supplier/updatePassword y funcion en getAvailabilityCourt

client/src/App.js, client/src/Components/Court/CourtList.jsx, client/src/Components/Navbar.jsx
Integramos creación de cancha en un botón dentro de la pestaña Canchas del panel de proveedor.
=> Panel de canchas

client/src/Components/Court/AvailabilityForm/HoursList.jsx, client/src/Components/Court/Context/AvailabilityContext.js, client/src/Components/Court/Context/CourtContext.js, client/src/Components/Court/CourtCard.jsx
Conexión de panel de supplier, sección de Canchas, con el back :)
=> conexion courts

client_mobile/babel.config.js, client_mobile/package-lock.json, client_mobile/package.json, client_mobile/src/components/Bookings/StyleBookings.jsx, client_mobile/src/components/CourtDetail/CourtDetail.jsx, client_mobile/src/components/CourtDetail/StyleCourtDetail.jsx, client_mobile/src/components/Courts/StyleCourts.jsx, client_mobile/src/components/FavoritesCourts/FavoritesCourts.jsx, client_mobile/src/components/FavoritesCourts/StyleFavoritesCourts.jsx, client_mobile/src/components/Home/Home.jsx, client_mobile/src/components/Home/HomeTab.jsx, client_mobile/src/components/Home/StyleHome.jsx, client_mobile/src/components/Landing/Landing.jsx, client_mobile/src/components/Landing/StylesLanding.jsx, client_mobile/src/components/Location/Location.jsx, client_mobile/src/components/Location/StylesLocation.jsx, client_mobile/src/components/Location/rutas.js, client_mobile/src/components/User/StylesUser.jsx, client_mobile/src/store/reducer/index.js
Arregle algunos errores que teniamos para verlo con expo go y agregue el mapa
=> Agrego el mapa

client_mobile/src/components/FavoritesCourts/StyleFavoritesCourts.jsx, client_mobile/src/components/Home/Home.jsx, client_mobile/src/components/Home/StyleHome.jsx, client_mobile/src/components/SearchBar/SearchBar.jsx, client_mobile/src/components/SearchBar/StyleSearchBar.jsx, client_mobile/src/store/actions/index.js, client_mobile/src/store/reducer/index.js
Estilos en Home, SearchBar y deje comentando en el action creator todas las rutas que tenemos que modificar para el deploy
=> SearchBar & Home Style - URLs Back Deploy comment

api/src/models/Bookings.js, api/src/routes/supplier/controllers/availability/getAvailabilityCourt.js, api/src/routes/user/controllers/booking/getBooking.js, api/src/routes/user/controllers/booking/postBooking.js
se agregan datos al modelo de booking, se modifica el get, si le paso active = true por query me trae solo las reservas con estado activo, ademas, ahora me trae la data de booking, mas la data de la respectiva cancha.
=> Mod booking1

client/src/Components/Court/AvailabilityForm/DayItem.jsx, client/src/Components/Court/AvailabilityForm/Form.jsx, client/src/Components/Court/Calendar/CalendarSection.jsx, client/src/Components/Court/Calendar/CourtCalendar.jsx, client/src/Components/Court/Context/AvailabilityContext.js, client/src/Components/Court/Context/CourtContext.js, client/src/Components/Court/CourtCard.jsx, client/src/Components/Court/CourtList.jsx, client/src/Components/Court/Courts.jsx
=> un poco de css

api/src/routes/user/controllers/getCourtsPriceSportZone.js, api/src/routes/user/court.js
Se agrega ruta de filtro, esta ruta trae las canchas, ya sea todas, por coordenadas, por deporte o por coordenadas y por deporte, segun los datos que se manden por query. Luego de obtener las canchas las filtra de mayor a menor precio, de menor a mayor precio o en un rango de precios, todo segun los datos que se manden por query.
Por ultimo queda pendiente la implementacion por coordenadas.
=> Ruta funcional, queda agregar el filtrado extra por coordenadas

api/src/routes/user/controllers/putFavSupplier.js, api/src/routes/user/controllers/register.js
Borre linea en register de usuario y otras cositas comentadas
=> Borre linea en register de usuario y otras cositas ocmentadas

client_mobile/src/components/BookingDetail/BookingDetail.jsx, client_mobile/src/components/BookingDetail/StylesBookingDetail.jsx, client_mobile/src/components/Bookings/Bookings.jsx, client_mobile/src/components/CourtDetail/CourtDetail.jsx, client_mobile/src/components/CourtDetail/StyleCourtDetail.jsx, client_mobile/src/components/FavoritesCourts/FavoritesCourts.jsx, client_mobile/src/components/FavoritesCourts/StyleFavoritesCourts.jsx, client_mobile/src/components/Message/Message.jsx, client_mobile/src/components/Message/StylesMessage.jsx, client_mobile/src/components/StackBooking/StackBooking.js, client_mobile/src/components/Supplier/Supplier.jsx, client_mobile/src/components/Suppliers/Suppliers.jsx, client_mobile/src/components/User/StylesUser.jsx, client_mobile/src/components/User/User.jsx, client_mobile/src/store/actions/index.js, client_mobile/src/store/reducer/index.js
Agrego funcionalidad de eliminar usuario, eliminar reserva, agrego estilos de los mensajes de alerta del back
=> Delete functionality and styles

client_mobile/src/components/Courts/Courts.jsx, client_mobile/src/components/Home/HomeTab.jsx, client_mobile/src/components/StackFavorites/StackFavorites.jsx, client_mobile/src/store/actions/index.js, client_mobile/src/store/reducer/index.js
Arreglo la selección de favoritos, ademas arreglo que cuando se buscaba en la barra de busqueda y se queria ingresar al detalle del provedor no aparecian las canchas, el mismo inconveniente ocurria con la seccion de favoritos. Ambos solucionados
=> Favorites Solution & Search Bar

client_mobile/src/store/actions/index.js
Para que sea mas simple, creo variable URL, para poder cambiar de localhost al deploy de forma mas rapida
=> Cambio URLs

api/src/routes/user/controllers/getFavSupplier.js, api/src/routes/user/controllers/getSupplier.js
=> Supplier sports

api/src/db.js, api/src/models/Bookings.js, api/src/routes/supplier/bookings.js, api/src/routes/supplier/controllers/availability/postAvailability.js, api/src/routes/supplier/controllers/createCourt.js, api/src/routes/supplier/controllers/getBookings.js, api/src/routes/supplier/controllers/register.js, api/src/routes/supplier_index.js
Entrega de info en post supplier, court y availability, se realiza relación (oneToMany) entre los modelos bookings y user, se elimina userId en modelo de User.
=> Cosas varias

client_mobile/src/components/BookingDetail/BookingDetail.jsx, client_mobile/src/components/CardBooking/CardBooking.js, client_mobile/src/components/Court/Court.jsx, client_mobile/src/components/CourtDetail/CourtDetail.jsx, client_mobile/src/components/FavoritesCourts/FavoritesCourts.jsx, client_mobile/src/components/SearchBar/SearchBar.jsx, client_mobile/src/components/Supplier/Supplier.jsx, client_mobile/src/components/Suppliers/Suppliers.jsx, client_mobile/src/components/User/User.jsx, client_mobile/src/store/actions/index.js
Cambio las imagenes para que aparezcan por defecto cuando estas en favoritos, cuando buscas, tambien en las canchas que les aparezca la del deporte. Ademas cambio en la ventana del usuario que cuando entra con google le bloquee ciertos campos.
=> Images & UserScreen

client/src/Components/Court/AvailabilityForm/Form.jsx, client/src/Components/Court/AvailabilityForm/HourItem.jsx, client/src/Components/Court/AvailabilityForm/HoursList.jsx, client/src/Components/Court/AvailabilityForm/helpers/functions.js
Controlé la selección de franjas horarias.
=> Control horarios

api/src/db.js, api/src/routes/supplier/controllers/getBookings.js
Se agrega ruta para historial q trae todo las reservas y se crearon filtros acumulativos segun lastname, idCourt, bookingCode, date y status y ordenamiento por fechas.
=> Rutas lu10

api/src/routes/user/controllers/getCourts.js, client_mobile/src/components/ConfirmBooking/ConfirmBooking.jsx, client_mobile/src/components/ConfirmBooking/StylesConfirmBooking.jsx, client_mobile/src/components/CourtDetail/CourtDetail.jsx, client_mobile/src/components/Courts/Courts.jsx, client_mobile/src/components/SearchBar/SearchBar.jsx, client_mobile/src/components/Supplier/StylesSupplier.jsx, client_mobile/src/components/Supplier/Supplier.jsx, client_mobile/src/components/Suppliers/Suppliers.jsx, client_mobile/src/store/actions/index.js
Creo una ventana para que le muestre al usuario el detalle de su reserva antes de realizar la seña, ademas arreglo problemas de la Searchbar y de Suppliers
=> ConfirmBookingScreen & Searchbar

api/src/routes/supplier/availability.js, api/src/routes/supplier/bookings.js, api/src/routes/supplier/controllers/availability/deleteAvailability.js, api/src/routes/supplier/controllers/getBookingsCourt.js
Rutas y Controladores: deleteAvailability, getBookingCourts
=> nuevas rutas

api/src/routes/supplier/controllers/getAllSupplier.js, api/src/routes/supplier/supplier.js, api/src/routes/user/controllers/getAllUsers.js, api/src/routes/user/user.js
Se suben rutas de gellAllUser y getAllSuppliers
=> Rutas lu11

api/src/db.js, api/src/models/Rating.js, api/src/models/Supplier.js, api/src/routes/supplier/controllers/rateSupplier.js, api/src/routes/supplier/rating.js, api/src/routes/supplier_index.js
Modelo, ruta y controlador de Rating. 
Agregué relación de 1 a 1 con Supplier en "db.js".
=> rating de un proveedor

client_mobile/src/components/BookingDetail/BookingDetail.jsx, client_mobile/src/components/Bookings/Bookings.jsx, client_mobile/src/components/CardBooking/CardBooking.js, client_mobile/src/components/CourtDetail/CourtDetail.jsx, client_mobile/src/components/RatingBooking/RatingBooking.jsx, client_mobile/src/components/RatingBooking/StylesRatingBooking.jsx, client_mobile/src/store/actions/index.js, client_mobile/src/store/reducer/index.js
Genero un Voucher para en caso de que cancele la reserva le quede disponible para una proxima reserva (faltaria mejorar el tema de que vea el dia y compare si la elimina y listo o si le da el voucher) Ademas hay un mensaje que esta medio mal, tambien a mejorar. El rating falta conexión con la ruta
=> Voucher and rating

client/src/Components/Court/AvailabilityForm/CourtInfo.jsx, client/src/Components/Court/AvailabilityForm/Form.jsx, client/src/Components/Court/AvailabilityForm/HoursList.jsx, client/src/Components/Court/Calendar/BookingItem.jsx, client/src/Components/Court/Calendar/CalendarSection.jsx, client/src/Components/Court/Calendar/CourtAvailability.jsx, client/src/Components/Court/Calendar/CourtCalendar.jsx, client/src/Components/Court/Context/AvailabilityContext.js, client/src/Components/Court/CourtCard.jsx, client/src/Components/Court/CourtList.jsx, client/src/Components/Court/Courts.jsx
Falta modificar color de botones de alertas para que se adapte al diseño.
Falta responsive de la parte de turnos.
=> responsive y alertas de seccion canchas

client/src/Components/CourtCreation.jsx, client/src/Css/Supplier Panel/courtcreation.css
Css y rpsta responsive de CreateCOurt
=> Css create court

client/src/Css/Supplier Panel/courtcreation.css
Pequeño cambio en la altura del css del form
=> fix altura form crear cancha
